export const initialState = {
    publicOffer: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        updateSuccess: false,
        loadingReport: false,
        reportSuccess: false,
        errorMessage: null,
        totalItems: -1,
        totalPages: 0,
    },
    sellerOffer: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        updateSuccess: false,
        addSuccess: false,
        errorMessage: null,
        totalItems: 0,
    },
    rentOffer: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        updateSuccess: false,
        addSuccess: false,
        errorMessage: null,
        totalItems: 0,
    },
    findOffer: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        updateSuccess: false,
        addSuccess: false,
        errorMessage: null,
        totalItems: 0,
    },
    myOffers: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        updateSuccess: false,
        addSuccess: false,
        deleteSuccess: false,
        errorMessage: null,
        totalItems: 0,
        totalPages: 0,
    },
    commentsOffer: {
        loading: false,
        entity: {},
        loadingEntities: false,
        entities: [],
        addSuccess: false,
        updateSuccess: false,
        deleteSuccess: false,
        reportSuccess: false,
        errorMessage: null,
        totalItems: -1,
        totalPages: 0,
    },
    userOffers: {
        loadingEntities: false,
        entities: [],
        totalItems: -1,
        totalPages: 0,
    },
    recentlyOffers: {
        loadingEntities: false,
        entities: [],
        totalItems: -1,
        totalPages: 0,
    },
    imagesOffers: {
        loadingEntities: false,
        entities: [],
        totalItems: -1,
        totalPages: 0,
    }
}
